export const sr = {
  loading: "Učitavanje...",
  noJobs: "Nema pronađenih poslova.",
  noConversations: "Nema razgovora.",
  noContracts: "Nemaš ugovora.",
  noProposals: "Nemaš poslanih ponuda.",
  noClientJobs: "Nemaš objavljenih poslova.",
  noProposalsForJob: "Nema ponuda za ovaj posao.",
  back: "Nazad",
  backToJobs: "Nazad na listu",
  backToInbox: "Nazad na inbox",
  backToContracts: "Nazad na ugovore",
  backToClientJobs: "Nazad na moje poslove",
  view: "Pogledaj",
  sendProposal: "Pošalji ponudu",
  previous: "Prethodna",
  next: "Sljedeća",
  page: "Strana",
  jobs: "Poslovi",
  apply: "Primijeni",
  allCategories: "Sve kategorije",
  allCities: "Svi gradovi",
  remoteOnly: "Samo remote",
  newest: "Najnoviji",
  budget: "Budžet",
  fixed: "Fiksni",
  hourly: "Po satu",
  jobNotFound: "Posao nije pronađen.",
  profileNotFound: "Profil nije pronađen.",
  conversationNotFound: "Razgovor nije pronađen.",
  contractNotFound: "Ugovor nije pronađen.",
  deactivated: "Nalog je deaktiviran.",
  report: "Prijavi",
  submitReport: "Pošalji prijavu",
  cancel: "Odustani",
  success: "Uspešno",
  error: "Greška",

  // Decision flow
  statusPending: "Na čekanju",
  statusAccepted: "Prihvaćeno",
  statusRejected: "Odbijeno",
  statusWithdrawn: "Povučeno",
  statusExpired: "Isteklo",
  statusPublished: "Objavljen",
  statusDraft: "Nacrt",
  statusClosed: "Zatvoren",
  accept: "Prihvati",
  reject: "Odbij",
  withdraw: "Povuci ponudu",
  rejectionReason: "Razlog odbijanja",
  rejectionReasonRequired: "Morate unijeti razlog odbijanja.",
  confirmReject: "Potvrdi odbijanje",
  deadlineExpired: "Rok je istekao",
  deadlineRemaining: "preostalo",
  otherFreelancerChosen: "Drugi izvođač je izabran.",
  proposalAccepted: "Ponuda je prihvaćena!",
  proposalRejected: "Ponuda je odbijena.",
  proposalWithdrawn: "Ponuda je povučena.",
  decisionDeadline: "Rok za odluku",
} as const;
